# Generated by Django 6.0.3 on 2026-03-06 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('clustered', 'Clustered'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_events', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
