# Generated by Django 6.0.3 on 2026-03-06 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('service_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('raw_log', models.TextField()),
                ('event_hash', models.CharField(max_length=64)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='incidents.incident')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.logfile')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='logs_logeve_timesta_d78206_idx'), models.Index(fields=['log_level'], name='logs_logeve_log_lev_83cd45_idx'), models.Index(fields=['service_name'], name='logs_logeve_service_5654dc_idx')],
            },
        ),
    ]
