# Generated by Django 6.0.3 on 2026-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
    ]
