# Generated by Django 6.0.3 on 2026-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_logfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='events_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logfile',
            name='events_parsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logfile',
            name='processing_time',
            field=models.FloatField(default=0),
        ),
    ]
