# Generated by Django 6.0.3 on 2026-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_logfile_events_failed_logfile_events_parsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logevent',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
