# Generated by Django 6.0.3 on 2026-03-06 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('severity_score', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logs.logfile')),
            ],
        ),
    ]
