# Generated by Django 6.0.3 on 2026-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
